SELECT
    B.FLAVOR
FROM FIRST_HALF A RIGHT OUTER JOIN JULY B 
    ON A.SHIPMENT_ID = B.SHIPMENT_ID
    AND A.FLAVOR = B.FLAVOR
GROUP BY B.FLAVOR
ORDER BY
    SUM(A.TOTAL_ORDER) + SUM(B.TOTAL_ORDER) DESC
FETCH FIRST 3 ROWS ONLY